# Generated by Django 4.2.4 on 2023-08-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate', models.CharField(max_length=200, verbose_name='Name and group of the Affiliated Firm')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Affiliation documents')),
            ],
        ),
        migrations.CreateModel(
            name='BankerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Name of Bank')),
                ('branch', models.CharField(max_length=200, verbose_name='Branch Name')),
                ('branch_code', models.CharField(max_length=200, verbose_name='Branch Code')),
                ('account', models.CharField(max_length=200, verbose_name='Account Number')),
                ('account_type', models.CharField(max_length=200, verbose_name='Account Type')),
                ('swift_code', models.CharField(max_length=200, verbose_name='Swift Code')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Bank confirmation letter')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('district', models.CharField(max_length=200, verbose_name='District')),
                ('village_town', models.CharField(max_length=200, verbose_name='Village/Town/City')),
                ('plot_unit', models.CharField(max_length=10, verbose_name='Plot/Unit No')),
                ('street_ward', models.CharField(max_length=200, verbose_name='Street/Locality/Ward')),
                ('postal', models.CharField(choices=[('p.o.box', 'P. O. Box'), ('private_bag', 'Private Bag')], max_length=200, verbose_name='P.O.Bo or Private Bag')),
                ('box_number', models.CharField(max_length=200, verbose_name='Box Number')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_provider', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=10, verbose_name='Are you a Local Provider/Contractor?')),
                ('business_type', models.CharField(max_length=200, verbose_name='Business Type')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Company')),
                ('cipa_registration', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=10, verbose_name='Are you Registered with CIPA?')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
                ('registration_date', models.DateTimeField(verbose_name='Date of Registration')),
                ('ownership', models.CharField(max_length=200, verbose_name='Ownership')),
                ('webpage', models.CharField(max_length=200, verbose_name='Webpage')),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
                ('bw_employees', models.CharField(max_length=200, verbose_name='Total Number of Botswana Citizens')),
                ('other_nationalities', models.CharField(max_length=200, verbose_name='TOtal Number of Other Nationalities')),
                ('total_employees', models.CharField(max_length=200, verbose_name='Total Employeed')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('cell_phone', models.CharField(max_length=200, verbose_name='Cell Phone no')),
                ('tel_phone', models.CharField(max_length=200, verbose_name='Telephone Phone no')),
                ('business_phone', models.CharField(max_length=200, verbose_name='Business Phone no')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('omang', models.CharField(max_length=200, verbose_name='Omang No')),
                ('expiry_date', models.DateTimeField(verbose_name='Validity of Card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SecondaryContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('cell_phone', models.CharField(max_length=200, verbose_name='Cell Phone no')),
                ('tel_phone', models.CharField(max_length=200, verbose_name='Telephone Phone no')),
                ('business_phone', models.CharField(max_length=200, verbose_name='Business Phone no')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('omang', models.CharField(max_length=200, verbose_name='Omang No')),
                ('expiry_date', models.DateTimeField(verbose_name='Validity of Card')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cipa_id', models.CharField(max_length=200, verbose_name='Enter CIPA Unique Identification Number (UIN) Without BW')),
            ],
        ),
        migrations.CreateModel(
            name='ShareholderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=200, verbose_name='Gender')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('omang', models.CharField(max_length=200, verbose_name='Omang No')),
                ('expiry_date', models.DateTimeField(verbose_name='Validity of Card')),
                ('passport_number', models.CharField(max_length=200, verbose_name='Passport Number')),
                ('work_permit', models.CharField(max_length=200, verbose_name='Work Permit')),
                ('percentage_shares', models.CharField(max_length=200, verbose_name='Percentage of Shares')),
                ('gov_employee', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=200, verbose_name='Government Employee')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Affiliation documents')),
                ('shareholders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.shareholders')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorPermenantStaffForeigner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('passport_number', models.CharField(max_length=200, verbose_name='Passport Number')),
                ('work_permit', models.CharField(max_length=200, verbose_name='Work Permit Number')),
                ('expiry_date', models.DateTimeField(verbose_name='Validity of Permit')),
                ('profession_trade', models.CharField(max_length=200, verbose_name='Profession/Trade')),
                ('position', models.CharField(max_length=200, verbose_name='Position in Firm')),
                ('qualification', models.CharField(max_length=200, verbose_name='Qualification')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Affiliation documents')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.employees')),
            ],
        ),
        migrations.CreateModel(
            name='SeniorPermenantStaffBW',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('omang', models.CharField(max_length=200, verbose_name='Omang No')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('profession_trade', models.CharField(max_length=200, verbose_name='Profession/Trade')),
                ('position', models.CharField(max_length=200, verbose_name='Position in Firm')),
                ('qualification', models.CharField(max_length=200, verbose_name='Qualification')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Affiliation documents')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.employees')),
            ],
        ),
        migrations.CreateModel(
            name='DirectorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('gender', models.CharField(max_length=200, verbose_name='Gender')),
                ('dob', models.DateTimeField(verbose_name='Date of Birth')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('omang', models.CharField(max_length=200, verbose_name='Omang No')),
                ('expiry_date', models.DateTimeField(verbose_name='Validity of Card')),
                ('passport_number', models.CharField(max_length=200, verbose_name='Passport Number')),
                ('work_permit', models.CharField(max_length=200, verbose_name='Work Permit')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Affiliation documents')),
                ('directors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.directors')),
            ],
        ),
    ]
