# Generated by Django 4.2.4 on 2023-09-03 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('home_phone', models.CharField(max_length=200, verbose_name='Home Phone No.:')),
                ('bus_phone', models.CharField(max_length=200, verbose_name='usiness Phone no.:')),
                ('mobile_no', models.CharField(max_length=10, verbose_name='Mobile no.:')),
                ('email', models.EmailField(max_length=254, verbose_name='Email:')),
                ('nationality', models.CharField(max_length=200, verbose_name='Nationality')),
                ('omang', models.CharField(max_length=200, verbose_name='Omang No.:')),
                ('expiry_date', models.DateTimeField(verbose_name='Expiry Date:')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asserts_value', models.CharField(max_length=200, verbose_name='Value of total of Company Assets in BWP:')),
                ('equipment_value', models.CharField(max_length=200, verbose_name="Value of Equipment's (in BWP) (Plant, Equipment's but Excluding hire items)")),
                ('capital', models.CharField(max_length=200, verbose_name='Paid Up Capital (in BWP)')),
                ('total_employees', models.CharField(max_length=200, verbose_name='Total Employeed')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_owner', models.CharField(max_length=200, verbose_name='Registered Owner')),
                ('ownership', models.CharField(choices=[('Owned', 'owned'), ('Leased', 'Leased')], max_length=200, verbose_name='Ownership')),
                ('registration_no', models.CharField(max_length=200, verbose_name='Registration No')),
                ('first_reg_date', models.DateTimeField(verbose_name='Date of First Registration')),
                ('make_model', models.CharField(max_length=200, verbose_name='Vehicle Make/Model')),
                ('prev_owner', models.CharField(max_length=200, verbose_name='Previous Owner')),
                ('description', models.CharField(max_length=200, verbose_name='Description of Vehicle')),
                ('present_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Present Value (In BWP)')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Ownership documents')),
                ('vehicle_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.vehicleequipment')),
            ],
        ),
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_private_no', models.CharField(max_length=200, verbose_name='P.O.Box / Private Bag:')),
                ('number', models.CharField(max_length=200, verbose_name='No.::')),
                ('address_line', models.CharField(max_length=200, verbose_name='Line Address 1:')),
                ('address_line2', models.CharField(max_length=200, verbose_name='Line Address 2:')),
                ('address_line3', models.CharField(max_length=200, verbose_name='Line Address 3:')),
                ('country', models.CharField(max_length=200, verbose_name='Country:')),
                ('village_town_city', models.CharField(max_length=200, verbose_name='Village/Town/City :')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.companysecretary')),
            ],
        ),
        migrations.CreateModel(
            name='PlantEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200, verbose_name='Name of the Owner')),
                ('ownership', models.CharField(choices=[('Owned', 'owned'), ('Leased', 'Leased')], max_length=200, verbose_name='Ownership')),
                ('registration_no', models.CharField(max_length=200, verbose_name='Registration No')),
                ('date_of_purchase', models.DateTimeField(verbose_name='Date of Purchase')),
                ('description', models.CharField(max_length=200, verbose_name='Description of Vehicle')),
                ('present_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Present Value (In BWP)')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Plant Equipment documents')),
                ('vehicle_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.vehicleequipment')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.CharField(max_length=200, verbose_name='Plot/Unit No.:')),
                ('street', models.CharField(max_length=200, verbose_name='Street:')),
                ('village_town_city', models.CharField(max_length=200, verbose_name='Village/Town/City :')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.companysecretary')),
            ],
        ),
        migrations.CreateModel(
            name='OnGoingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project name')),
                ('details', models.CharField(max_length=200, verbose_name='Project Details')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('client_representation', models.DateTimeField(verbose_name='Client Representation')),
                ('contact_number', models.CharField(max_length=200, verbose_name='Client contact number')),
                ('date_started', models.DateField(verbose_name='Date Started')),
                ('locality', models.CharField(choices=[('bobonong', 'Bobonong'), ('bokaa', 'Bokaa'), ('borolong', 'Borolong'), ('chadibe', 'Chadibe'), ('dukwi', 'Dukwi')], max_length=200, verbose_name='Locality')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value of Contract (In BWP)')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Project documents')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.projects')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEquipments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_furniture', models.CharField(max_length=200, verbose_name='Office Furniture')),
                ('present_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Present Value (In BWP)')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Affiliation documents')),
                ('vehicle_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.vehicleequipment')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project name')),
                ('details', models.CharField(max_length=200, verbose_name='Project Details')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('client_representation', models.DateTimeField(verbose_name='Client Representation')),
                ('contact_number', models.CharField(max_length=200, verbose_name='Client contact number')),
                ('date_completed', models.DateField(verbose_name='Date Completed')),
                ('locality', models.CharField(choices=[('bobonong', 'Bobonong'), ('bokaa', 'Bokaa'), ('borolong', 'Borolong'), ('chadibe', 'Chadibe'), ('dukwi', 'Dukwi')], max_length=200, verbose_name='Locality')),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Value of Contract (In BWP)')),
                ('attachments', models.FileField(upload_to='uploads/% Y/% m/% d/', verbose_name='Attachments e.g Project documents')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crms.projects')),
            ],
        ),
    ]
